### ISSUE TITLE
Known bugs in taped out chip (tapeout1)

### ISSUE THREAD

**Issue by alexcarsello** [StanfordAHA/CGRAGenerator#122]
These are bugs we've found in the taped out chip. Checked box means the issue has been fixed in dev/master.

- [x] 1 bit inputs don't work
- [x]  arithmetic shift sign extension bug

**Comment by steveri** [comment]
I started a wiki page for the bugs https://github.com/StanfordAHA/CGRAGenerator/wiki/Bugs

**Comment by steveri** [comment]
Bugs have been fixed and documented. Closing the issue
