### ISSUE TITLE
Missing output registers.

### ISSUE THREAD

**Issue by steveri** [StanfordAHA/CGRAGenerator#18]
Previously, CGRA was built such that all output wires were registered.  Beginning with nbdev1 that seemed not to be the case.

I think I found the problem, however; the previous run.csh driver had an environment variable
# setenv CGRA_GEN_ALL_REG 1

that got commented out when run.csh changed to run.sh.  The near-term fix is probably to restore the enviornment variable in run.csh e.g. now that it's bash instead of csh it should be something like

export CGRA_GEN_ALL_REG=1

**Comment by nikhilbhagdikar** [comment]
This variable is not supposed to be the default. It is a WA till the placer is fixed for register placement.

**Comment by steveri** [comment]
that's fine; this seems to be under control, i'm going to close it out
