### ISSUE TITLE
Factor genesis setup logic out of `bin/generate.csh` into separate script

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/CGRAGenerator#19]
Perhaps a script `bin/setup_genesis.csh` that installs genesis if needed (or finds the current installation) and then sets the proper environment variables.

`generate.csh` could still refer to this script if needed (i.e. it could prompt the user to run it if genesis doesn't seem to be setup properly, or it could just run it automatically like it does now).

This enables us to decouple the installation and configuration of the environment for genesis from the actual logic to run specific generators.

**Comment by steveri** [comment]
Yes, although to be generally useful we'd probably need two scripts setup_genesis.csh and setup_genesis.sh, which of course would need to be "source'd" and not run b/c they are setting env variables...

and/or maybe we could build a "bin/Genesis.pl" wrapper that would supercede the existing Genesis.pl, where the new wrapper is a script that checks your environment and does all the perquisite setup before executing the *real* Genesis.pl inside the wrapper, if you know what I mean...including e.g. doing a "git clone" to e.g. /tmp in the case that Genesis does not yet exist etc. ... sort of like what generate.csh does before it then calls top/run.csh ...

**Comment by steveri** [comment]
I think I did this, sorta.  Anyway, this issue has timed out by now.
