### ISSUE TITLE
cgra_info.txt: missing quotes in gout/src tag (nbdev1)

### ISSUE THREAD

**Issue by steveri** [StanfordAHA/CGRAGenerator#21]
[nikhil we already discussed this via email but i am recording it here now so it doesn't get lost...]    

nbdev1 is emitting this in the cgra_info.txt file:
        <gout feature_address='5'>
          <src sel=0>valid</src>
          <src sel=1>almost_full</src>
        </gout>

...the lack of quote marks for the "sel" parms is making the xml interpreter choke...can we please change it to
        <gout feature_address='5'>
          <src sel='0'>valid</src>
          <src sel='1'>almost_full</src>
        </gout>

**Comment by nikhilbhagdikar** [comment]
This should now be fixed.

**Comment by steveri** [comment]
yes i think we're good with this now
