### ISSUE TITLE
errant comma in jtag.vp

### ISSUE THREAD

**Issue by steveri** [StanfordAHA/CGRAGenerator#22]
hardware/generator_z/jtag/jtag.vp has a comma at the end of its port list, and verilator doesn't like it.  Can we please remove the comma after tms, i.e. change it from this:

> module `mname` (
> clk, reset,
> config_addr_out,
> config_data_out,
> tdi,
> tdo,
> tms,
> );

to this:

> module `mname` (
> clk, reset,
> config_addr_out,
> config_data_out,
> tdi,
> tdo,
> tms
> );
> 

```

**Comment by alexcarsello** [comment]
Done. Though I've been working in jtag_template.vp, not jtag.vp
