### ISSUE TITLE
nbdev4/cgra_info/mem: "almost_full_count" and "depth"

### ISSUE THREAD

**Issue by steveri** [StanfordAHA/CGRAGenerator#29]
In cgra_info for nbdev3, in the mem tile tags, it was called "almost_full_count" and "fifo_depth"; now it's just "almost_count" and "depth"...was that on purpose?

```
1511,1514c1497,1500
<        <almost_full_count bith='18' bitl='16'>0</almost_full_count>
<        <fifo_depth bith='15' bitl='3'>0</fifo_depth>
---
>        <almost_count bith='19' bitl='16'>0</almost_count>
>        <depth bith='15' bitl='3'>0</depth>

```

**Comment by makaimann** [comment]
I have no idea. That's just a name for us, so it doesn't matter much either way.

**Comment by steveri** [comment]
Cleaning up old issues...this has long since been dealt with...
