### ISSUE TITLE
IO CGRA info 

### ISSUE THREAD

**Issue by cdonovick** [StanfordAHA/CGRAGenerator#36]
In the nbdev3 CGRA info given us there was no bitl, bith or feature address configuring the IO tiles. While I understand that all of these are assumed to be 0, this qualifies as secret outside knowledge.

**Comment by steveri** [comment]
This got fixed...right?  Format currently looks like this:
```
  <tile type='io1bit' tile_addr='0x2' row='0' col='2' tracks='BUS1:1 BUS16:0' name='pad_S3_T0'>
  ...
    <tri feature_address='0' reg_address='0' bitl='0' bith='0'>
    ...
    <mux feature_address='0' reg_address='0' bitl='1' bith='1'>
    ...
```
