### ISSUE TITLE
[pe_comp] ge signed issue

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/CGRAGenerator#57]
0 >= 0 should be 1, but fails in signed mode (res_p is 0)
```
[opcode=24, Test Iteration 0] Inputs: op_a=0, op_b=0, op_d_p=0
    expected_res=0, actual_res=0
    expected_res_p=1, actual_res_p=0
```

Could be related to https://github.com/StanfordAHA/CGRAGenerator/issues/56

**Comment by kong0329** [comment]
@leonardt I guess equivalent checking is missing in gte (which was in lte)
It's an easy fix, but dev is broken now, so I will fix it tomorrow.

**Comment by kong0329** [comment]
@leonardt It is not related to #56

**Comment by kong0329** [comment]
@leonardt Can you check gte again as well with correct opcode?

**Comment by leonardt** [comment]
This was fixed with correct opcode
