### ISSUE TITLE
cgra_info does not contained the 'signed' field for op.

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/CGRAGenerator#60]
This is blocking Halide/mapper unit tests.

**Comment by kong0329** [comment]
`        <opcode reg_address='0xff' bith='6' bitl='6'>is_signed</opcode>`
Is adding this field to cgra_info good for unittest?

**Comment by rdaly525** [comment]
Need confirmation from @cdonovick to verify this is sufficient. Also @kong0329 can you add the flag_sel field as well?

**Comment by kong0329** [comment]
Got it.
Since it is similar to signed bit, I will add after confirmation from @cdonovick .

**Comment by steveri** [comment]
So...to be clear...in context, the info will look like this(?):

```
    <pe feature_address='0'>
        <opcode reg_address='0xff' bith='6' bitl='6'>is_signed</opcode>
        <opcode reg_address='0xff' bith='5' bitl='0'>
            <op sel='0x00' name='add'>
                pe_out_res=op_a+op_b+op_d
                comp_res_p=(op_a+op_b+op_d) gte 2^16
            </op> 
            <op sel='0x01' name='sub'>
                pe_out_res=op_a+~op_b+1
                comp_res_p=(op_a+~op_b+1) gte 2^16
            </op> 
             ...
        </opcode>
```

**Comment by cdonovick** [comment]
Looks good to me

**Comment by kong0329** [comment]
@steveri Yes, info will look like that with additional flag_sel bits as well

**Comment by kong0329** [comment]
Added flag_sel, signed, and other configuration registers to cgra_info.
Merged to dev branch.
Close this issue.
