### ISSUE TITLE
Issue with add op with flag 0xD [Z | (N != V)]

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/CGRAGenerator#61]
`flag_sel = 0xD` so we expect `res_p` to be `Z | (N != V)`

```
❯ pytest -k "test_op[add-strategy1-13]"
[Test Iteration 0] Inputs: data0=8806, data1=17ea, bit0=0, bit1=0, bit2=0
    expected_res=9ff0, actual_res=9ff0
    expected_res_p=1, actual_res_p=1
[Test Iteration 1] Inputs: data0=2eb, data1=521d, bit0=0, bit1=1, bit2=1
    expected_res=5508, actual_res=5508
    expected_res_p=0, actual_res_p=0
[Test Iteration 2] Inputs: data0=82cc, data1=3f15, bit0=1, bit1=0, bit2=0
    expected_res=c1e2, actual_res=c1e2
    expected_res_p=1, actual_res_p=1
[Test Iteration 3] Inputs: data0=70bf, data1=9864, bit0=0, bit1=0, bit2=0
    expected_res=923, actual_res=923
    expected_res_p=0, actual_res_p=1
```

`data0 = 0x70bf = 0111 0000 1011 1111`
`data1 = 0x9864 = 1001 1000 0110 0100`
`res = 0x923 = 0000 1001 0010 0011`

So, we expected `Z = 0` because the output is not zero.
We expect `N = 0` because `res` is positive (sign bit is not set)
We expected `V = 0` because the sign bits are mismatched, so we cannot have signed overflow in addition

So, `N != V == 0` since they are both 0, and `Z` is 0 so `res_p` should be 0.

Here's another failing example

```
❯ pytest -k "test_op[add-strategy1-13]"
[Test Iteration 0] Inputs: data0=ab86, data1=cacd, bit0=0, bit1=1, bit2=1
    expected_res=7653, actual_res=7653
    expected_res_p=1, actual_res_p=1
[Test Iteration 1] Inputs: data0=9aa2, data1=8a9, bit0=1, bit1=0, bit2=1
    expected_res=a34c, actual_res=a34c
    expected_res_p=1, actual_res_p=1
[Test Iteration 2] Inputs: data0=4d10, data1=4ddd, bit0=0, bit1=1, bit2=1
    expected_res=9aed, actual_res=9aed
    expected_res_p=0, actual_res_p=1
```

`data0 = 0x4d10 = 0100 1101 0001 0000`
`data1 = 0x4ddd = 0100 1101 1101 1101`
`res = 0x9aed = 1001 1010 1110 1101`

Here, we get `Z = 0`, `N = 1` because `res` is negative, `V = 1` because the result of adding two positive numbers gave us a negative number, so `N != V == 0`

Let me know if there's an issue with my logic here.

**Comment by leonardt** [comment]
Looks like it works when the `signed` mode is set, I'm guessing the behavior of the `V` flag in unsigned mode is undefined

**Comment by tema8** [comment]
0x70bf + 0x9864 = 0x10923 

So,  C = 1 and V would be 1 for unsigned add. 
Make sure you set 'is_signed' field(op_code[6]) to the correct value

**Comment by leonardt** [comment]
@tema8 so C == V for unsigned?
