### ISSUE TITLE
ABS specification for unsigned mode

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/CGRAGenerator#72]
Right now `abs` treats the input as a signed number regardless of the current mode (`diff_sign ? op_a : add_res[0]`) and returns the negation if the top (sign) bit is set, so with large unsigned numbers in unsigned mode, this results in a negation even though we're in unsigned mode.

Should the `abs` behavior be defined for unsigned mode?

**Comment by leonardt** [comment]
I think the RTL change would look something like `(is_signed & diff_sign) ? op_a : add_res[0]`

**Comment by steveri** [comment]
... or maybe just      
 `is_signed ? op_a : add_res[0];`   
?

**Comment by steveri** [comment]
I guess there's no reason we couldn't just go ahead and do this...I have implemented and pushed the change in dev...now waiting for travis to confirm the change...
