### ISSUE TITLE
cgra_info should include default values

### ISSUE THREAD

**Issue by steveri** [StanfordAHA/CGRAGenerator#79]
cgra_info should include default values.  Also:
* separate 'reg' designation from 'mux'
* include reg_address as part of config address
* clean up, make consistent 'configh/configl' vs. 'bith/bitl'

Old:
```
        <mux snk='out_BUS1_S0_T0' reg='1' configh='1' configl='0' configr='40'>
          <src sel='0'>in_BUS1_S1_T0</src>
          <src sel='1'>in_BUS1_S2_T0</src>
          <src sel='2'>in_BUS1_S3_T0</src>
          <src sel='3'>pe_out_res_p</src>
        </mux>

```
Proposal:
```
        <mux snk='out_BUS1_S0_T0' reg_address='0' bith='1' bitl='0' default='3'>
          <src sel='0'>in_BUS1_S1_T0</src>
          <src sel='1'>in_BUS1_S2_T0</src>
          <src sel='2'>in_BUS1_S3_T0</src>
          <src sel='3'>pe_out_res_p</src>
        </mux>
        <reg src='out_BUS1_S0_T0' reg_address='1' bith='8' bitl='8' default='0' />
```

**Comment by alexcarsello** [comment]
Looks like it broke some tests... @steveri is this your stuff?

From the Travis log:
`gen_bsa_files.csh:
  $gen/bitstream/bsbuilder/bsbuilder.py mem_lbuf09.bsb > mem_lbuf09.bsa
Traceback (most recent call last):
  File "/home/travis/build/StanfordAHA/CGRAGenerator/bitstream/bsbuilder/bsbuilder.py", line 1287, in <module>
    main()
  File "/home/travis/build/StanfordAHA/CGRAGenerator/bitstream/bsbuilder/bsbuilder.py", line 206, in main
    if bs_connection(tileno, line, DBG-1):
  File "/home/travis/build/StanfordAHA/CGRAGenerator/bitstream/bsbuilder/bsbuilder.py", line 385, in bs_connection
    cwt = cgra_info.connect_within_tile(tileno, Tlhs, Trhs, max(0,DBG-1))
  File "/home/travis/build/StanfordAHA/CGRAGenerator/bitstream/bsbuilder/../decoder/lib/cgra_info.py", line 1367, in connect_within_tile
    parms = find_mux(tile, src_cgra, snk_cgra, DBG)
  File "/home/travis/build/StanfordAHA/CGRAGenerator/bitstream/bsbuilder/../decoder/lib/cgra_info.py", line 695, in find_mux
    return get_encoding(tile,bb,mux,msrc,DBG-1)
  File "/home/travis/build/StanfordAHA/CGRAGenerator/bitstream/bsbuilder/../decoder/lib/cgra_info.py", line 734, in get_encoding
    parms['configh']= getnum(mux.attrib['configh'])
KeyError: 'configh'
Traceback (most recent call last):
  File "/home/travis/build/StanfordAHA/CGRAGenerator/testdir/unit_tests/utest.py", line 588, in <module>
    main()
  File "/home/travis/build/StanfordAHA/CGRAGenerator/testdir/unit_tests/utest.py", line 125, in main
    my_syscall(mydir+'/gen_bsa_files.csh')
  File "/home/travis/build/StanfordAHA/CGRAGenerator/testdir/unit_tests/utest.py", line 19, in my_syscall
    assert False, "\nSubprocess call failed:\n%s" % cmd
AssertionError: 
Subprocess call failed:
/home/travis/build/StanfordAHA/CGRAGenerator/testdir/unit_tests/gen_bsa_files.csh
make: *** [test_unit] Error 13`

**Comment by steveri** [comment]
Yes, that's me.  The relevant error is this, where my config_info decoder is still looking for 'configh':
```
"...cgra_info.py", line 734, in get_encoding parms['configh']= getnum(mux.attrib['configh']) 
KeyError: 'configh' 
```
I will work on fixing the error, assuming you don't mind me mucking around in your branch...I guess it's 'default_cgra_info' yes?

**Comment by alexcarsello** [comment]
default cb config values are now in cgra_info.txt, too

**Comment by steveri** [comment]
oops looks like, in the process, all the 'snk' fields got turned into 'out':

BEFORE:
```
    <cb feature_address='4' bus='BUS1'>
        <sel_width>4</sel_width>
        <mux snk='bit0'>
```

AFTER:
```
    <cb feature_address='4' bus='BUS1'>
        <sel_width>4</sel_width>
        <mux snk='out' default='13'>
```

```
% diff cgra_info.txt.{old,new}
383c383
<         <mux snk='bit0'>
>         <mux snk='out' default='13'>
402c402
<         <mux snk='bit1'>
>         <mux snk='out' default='13'>
421c421
<         <mux snk='bit2'>
>         <mux snk='out' default='13'>
440c440
<         <mux snk='cg_en'>
>         <mux snk='out' default='13'>
459c459
<         <mux snk='data0'>
>         <mux snk='out' default='13'>
...
```

**Comment by alexcarsello** [comment]
Hm. I didn't change that part of the cb code
If you look at cb.vp in dev and master you'll see this:
`//; # ###############################################
//; # Setup input mux
//; # ###############################################
//;my $filename = "CB".$self->mname();
//;open(CBINFO, ">$filename") or die "Couldn't open file $filename, $!";
//;print CBINFO "        <sel_width>$mux_sel_bit_count</sel_width>\n";
//;#print CBINFO "        <has_constant>$has_constant</has_constant>\n";
**//;print CBINFO "        <mux snk='out'>\n";**

However, I do see the the cgra_info still had mux snk=*correct input port name*. Looks like the tile that contains the cb goes in and replaces "out" with the proper port name, but having the default on the same line broke that. I just put in a quick fix which just puts the default on a separate line.
`

**Comment by steveri** [comment]
What a crazy thing!
Anyway...Looks like it passed this time
https://travis-ci.org/StanfordAHA/CGRAGenerator/builds/384149914

**Comment by steveri** [comment]
Okay I think the defaults are in there by now...I just checked the latest cgra_info.xml and I see things like this:

```
    <cb feature_address='5' bus='BUS1'>
        <default>13</default>

    <sb feature_address='9' bus='BUS1'>
        <mux snk='out_BUS1_S0_T0' reg_address='0' bith='1' bitl='0' default='3'>
         <reg src='out_BUS1_S0_T0' reg_address='1' bith='8' bitl='8' default='0' />
```
