### ISSUE TITLE
CGRA Hangs When I try to load conv_bw?

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/CGRAGenerator#80]
@steveri @alexcarsello I'm running the dev branch of the CGRA from a few weeks ago (modified so that it actually gets through VCS). It works on:

* pointwise multiply by 2
* conv_2_1
* conv_3_1

but when I try to run it conv_bw the simulator seems to hang when it gets to line:

```bash
00020049 00000000
```

Has anyone run conv_bw on the CGRA in VCS or NCsim? Any ideas about what the problem might be?

**Comment by alexcarsello** [comment]
Hmm. I've run tests with conv_bw, and I did not have this issue. I'll look into it.

**Comment by dillonhuff** [comment]
Do you remember what branch you ran those tests on? I know conv_bw runs through verilator on travis, have you run conv_bw through the CGRA in NCsim or verilator?

**Comment by alexcarsello** [comment]
I've run it using ncsim in dev. Which bitstream are you using? I had an older conv_bw bitstream saved in my test directory (not totally sure where it's from), and it's working. However, I just tried the one in the TestBenchGenerator repo, and it's not working for me. The simulation doesn't freeze, but I'm getting zeros out.

**Comment by steveri** [comment]
Yes I also get zeroes from TestBenchGenerator/tests/conv_bw/conv_bw_pnr_bitstream

Does anyone know where these bitstreams came from and/or if they are actually supposed to work?

**Comment by dillonhuff** [comment]
I'm using the conv_bw bitstream from master. conv_3_1 seems to work correctly, but conv_bw does not.

I have no idea who created them.

**Comment by steveri** [comment]
There should be a working bitstream here, on kiwi:

/nobackup/steveri/github/CGRAGenerator/bitstream/bsbuilder/testdir/examples/conv_bw_reordered.bs

**Comment by steveri** [comment]
Also this, which I cut'n'pasted from https://travis-ci.org/StanfordAHA/CGRAFlow/jobs/386599479

/nobackup/steveri/github/CGRAGenerator/bitstream/bsbuilder/testdir/examples/conv_bw_travis.bs

**Comment by steveri** [comment]
io.json file associated with conv_bw_reordered.bs can be found here:

/nobackup/steveri/github/CGRAGenerator/verilator/generator_z_tb/io/s2in_s0out.io.json

```
% cat io/s2in_s0out.io.json 
{
    "io16_out_0_0": {
        "bits": {
            "0": "pad_S0_T15",
            "1": "pad_S0_T14",
            "2": "pad_S0_T13",
            "3": "pad_S0_T12",
            "4": "pad_S0_T11",
            "5": "pad_S0_T10",
            "6": "pad_S0_T9",
            "7": "pad_S0_T8",
            "8": "pad_S0_T7",
            "9": "pad_S0_T6",
            "10": "pad_S0_T5",
            "11": "pad_S0_T4",
            "12": "pad_S0_T3",
            "13": "pad_S0_T2",
            "14": "pad_S0_T1",
            "15": "pad_S0_T0"
        },
        "mode": "out",
        "width": 16
    },
    "io16in_in_arg_1_0_0": {
        "bits": {
            "0": "pad_S2_T15",
            "1": "pad_S2_T14",
            "2": "pad_S2_T13",
            "3": "pad_S2_T12",
            "4": "pad_S2_T11",
            "5": "pad_S2_T10",
            "6": "pad_S2_T9",
            "7": "pad_S2_T8",
            "8": "pad_S2_T7",
            "9": "pad_S2_T6",
            "10": "pad_S2_T5",
            "11": "pad_S2_T4",
            "12": "pad_S2_T3",
            "13": "pad_S2_T2",
            "14": "pad_S2_T1",
            "15": "pad_S2_T0"
        },
        "mode": "in",
        "width": 16
    }
}           

```

**Comment by steveri** [comment]
..and for /nobackup/steveri/github/CGRAGenerator/bitstream/bsbuilder/testdir/examples/conv_bw_travis.bs it looks like we're using S2 for the input pads and out on S3...?  You can look at the travis log and confirm

**Comment by dillonhuff** [comment]
I could not find
```/nobackup/steveri/github/CGRAGenerator/bitstream/bsbuilder/testdir/examples/conv_bw_travis.bs```
on kiwi.

I ran the conv_bw bitstream in 

``` /nobackupkiwi/steveri/github/CGRAGenerator/bitstream/bsbuilder/testdir/examples```

And got a non-zero result out of S3. However for an image where every pixel is 3 the output at each cycle in steady state is 234 = 3*78, but the sum of all the constants that I see in the conv_bw file is 120, so I would expect the result to be 360.

Do you know what the correct behavior of conv_bw is? Are there gold examples that I can compare to?

**Comment by steveri** [comment]
Hm note the pixels max value is 255 so e.g. 255 + 10 = 9; this mod255 behavior happens for every subcomputation so the result is not going to be as simple/obvious as you may have hoped!  

Also note 3x78 != 234 :)

Also: in testdir/examples you can see sample input conv_bw_input.raw and  conv_bw_halide_out.raw

**Comment by steveri** [comment]
This is what I got when I ran conv_bw on an all-three input (below).  Once it got past the boundary conditions, the steady state answer was 104, which is 360 mod 256.  Is that what you wanted?  Note 234 is an intermediate-state that it passes through b/c of edge conditions...

```
od -t u1 io/threes.raw
0000000   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
*
0001000
...
0000000   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
*
0001000
od -t u1 /tmp/run.csh.8Fq/output.raw
0000000  57 105 144 144 144 144 144 144 144 144 144 144 144 144 144 144
0000020 144 144 144 144 144 144 144 144 144 144 144 144 144 144 144 144
*
0000100 198 198 234 234 234 234 234 234 234 234 234 234 234 234 234 234
0000120 234 234 234 234 234 234 234 234 234 234 234 234 234 234 234 234
*
0000200  29  71 104 104 104 104 104 104 104 104 104 104 104 104 104 104
0000220 104 104 104 104 104 104 104 104 104 104 104 104 104 104 104 104
*
0001000
...
0000220 104 104 104 104 104 104 104 104 104 104 104 104 104 104 104 104
*
0001000

```

**Comment by dillonhuff** [comment]
Thanks for looking into this Steve.

The mod256 thing is strange to me. I thought we were doing 16 bit arithmetic inside the CGRA so there would be plenty of extra room to avoid overflow?

Also which conv_bw bitstream were you running on when you generated the results in your last post? And is the all 3s input file you used now in the CGRAGenerator repo?

**Comment by steveri** [comment]
Yes you are correct (and I was wrong); internally the arithmetic is 16 bits but the test harness only emits bytes so that's where the truncation occurs.

As for the zeroes at the end of the bitstream: ???????

How did you think to do that?  And why/how does it fix the problem?

I wonder if maybe this is also a test harness problem...maybe it ignores the final entry in the bitstream somehow?

**Comment by dillonhuff** [comment]
I assumed address 00000000 was not used, so I assumed that adding that line would ensure that the testbench would not be setting any data after the bitstream was loaded.

I have no idea how it fixes the problem. Also Ross mentioned to me that the memory configuration must be loaded last in the bitstream. Is that true? And if so why? Perhaps this is a bitstream ordering issue.

**Comment by steveri** [comment]
> memory configuration must be loaded last in the bitstream

Yes that is the safest thing to do.  It's bad if e.g. WEN wiggles off and back on again after the linebuffer has been set up, which can happen as wires get unconnected and reconnected during the routing portion of the bitstream setup.  It messes up the internal state of the linebuffer and you wind up with e.g. a 7-deep linebuffer instead of the 10-deep that you originally configured (this has actually happened).  Also if a LUT is set up as an inverter, it is easy during routing for the wires to pass through a state such that the inverter output is connected directly to its input, which makes the simulator hang forever waiting for the value to stabilize to a 1 or 0 (also has actually happened).

So now the rule for configuration is a) do the switchbox and connection box wiring FIRST and then b) do the tile setup for LUTs, memories (e.g. WEN), ALU ops etc.  For this reason I have a csh script CGRAGenerator/verilator/generator_z_tb/bion/reorder.csh that takes any bitstream config file 'before.bs' and transforms it for the proper order (ish):

```
grep -v '#' before.bs | egrep . > tmp (to remove comments and blank lines)
cat tmp | egrep -v '^..00' > tmp.1
cat tmp | egrep    '^..00' > tmp.2
cat tmp.1 tmp.2 > after.bs
```

**Comment by steveri** [comment]
PS In thinking about this a little more I strongly suspect that your test harness is not reading the final line in a given bitstream configuration file...is this possible; and/or do you have any way to verify one way or the other?

**Comment by dillonhuff** [comment]
When I print out the lines in the testbench I see the final line printed out when I display config_addr and config_data, so I dont think ignoring the last line is the issue.

**Comment by steveri** [comment]
closing stale issue
