### ISSUE TITLE
Several more unsupported ops harris:

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/CGRAGenerator#94]
The bsbuilder does not seem to support a few more ops that are in harris:

* ash
* sma
* sge
* slt

@steveri are these ops supported by the PE tile I don't see opcodes for them.

**Comment by steveri** [comment]
Hm I thought this had been fixed.  I will look at it when I am in the office tomorrow...

**Comment by steveri** [comment]
I believe this is fixed, can you confirm?  Then we can close this one.

**Comment by dillonhuff** [comment]
I did not see this error when I ran on your copy of harris, so I assume its fixed.
