### ISSUE TITLE
bsbuilder crashes on harris.bsb with bad connection?

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/CGRAGenerator#95]
I inserted filler opcodes for the operations mentioned in #94 to see what else is broken in the pipeline.

With those filler opcodes bsbuilder gets further on harris, but the crashes with the error:

```bash
dhuff@kiwi:~/CGRAGenerator/bitstream/bsbuilder/testdir$ ../bsbuilder.py < harris.bsb
690 found snk sb_wire_in_1_BUS16_S3_T4
690 found src in_0_BUS16_S0_T4
690 found src in_0_BUS16_S2_T4
690 found src in_0_BUS16_S3_T4
690 found src rdata

Tile 0x59: Cannot connect 'sb_wire_out_1_BUS16_S3_T4' to 'sb_wire_in_1_BUS16_S3_T4'
sb_wire_out_1_BUS16_S3_T4 can connect to
    out_0_BUS16_S0_T4
    out_0_BUS16_S2_T4
    out_0_BUS16_S3_T4
sb_wire_in_1_BUS16_S3_T4 can connect to
    in_0_BUS16_S0_T4
    in_0_BUS16_S2_T4
    in_0_BUS16_S3_T4
    rdata

```

@steveri have you seen this error before?

**Comment by dillonhuff** [comment]
After looking in to this more it looks like the problem is this segment of a route in harris.bsb:

```bash
T89_in_s1t4 -> T89_out_s1t4
```

This path maps from an input to an output on the same side and track, does the switching network support this?

**Comment by steveri** [comment]
Another thing that I thought I fixed before I left! I will look at it when I am in the office tomorrow...

**Comment by steveri** [comment]
Just to make sure we're on the same page...this is the error I get when I run the latest version, from the beginning, in branch "harris" (note json2dot.py may have changed since the last time you generated a dot file....)

```
% cd CGRAGenerator/bitstream/bsbuilder/testdir/harris
% CGRAGenerator/testdir/graphcompare/json2dot.py < harris.json > harris.dot
% ../../serpent.py -v harris.dot -o harris.bsb > serpent.log
% ../../bsbuilder.py < harris.bsb
Traceback (most recent call last):
  File "../../bsbuilder.py", line 1391, in <module>
    main()
  File "../../bsbuilder.py", line 212, in main
    if bs_connection(tileno, line, DBG-1):
  File "../../bsbuilder.py", line 398, in bs_connection
    % Trhs
AssertionError: ERROR Uh oh looks like more than one guy wants to write 'T63_out_s1t4'

```

**Comment by steveri** [comment]
Okay I fixed the "more than one guy wants to write 'T63_out_s1t4'" error (see prev comment) and now I am getting the "Tile 0x59: Cannot connect" error for which this issue was originally opened.  I will look at that next...

**Comment by steveri** [comment]
Problem seems to be here, in harris.bsb (thanks Dillon for finding it)

```
# lb_p3_cim_stencil_update_stream$lbmem_1_0::smax_782_783_784$cgramax.data.in.1
  T121_mem_out -> T121_out_s3t4
  T89_in_s5t4 -> T89_out_s7t4
  T89_in_s1t4 -> T89_out_s1t4 ****
  T89_in_s7t4 -> T89_out_s6t4
  T106_in_s0t4 -> T106_out_s1t4
  T106_out_s1t4 -> T106_op2
```
Cannot connect "T89_in_s1t4 -> T89_out_s1t4" duh.  In fact this whole path from side 5 to side 6 in tile 89 (0x59):

```
  T89_in_s5t4 -> T89_out_s7t4
  T89_in_s1t4 -> T89_out_s1t4
  T89_in_s7t4 -> T89_out_s6t4
```

should probably instead just be a single mux:

`  T89_in_s5t4 -> T89_out_s6t4`

so the correct sequence would then be

```
# lb_p3_cim_stencil_update_stream$lbmem_1_0::smax_782_783_784$cgramax.data.in.1
  T121_mem_out -> T121_out_s3t4
  T89_in_s5t4 -> T89_out_s6t4
  T106_in_s0t4 -> T106_out_s1t4
  T106_out_s1t4 -> T106_op2
```

Could maybe fix temporarily by directly editing the bsb file (hint hint) but first I will check and see if there is a quick serpent fix...

**Comment by steveri** [comment]
Fixed.  Also: generated a bitstream!  See
`/nobackup/steveri/github/CGRAGenerator/bitstream/bsbuilder/testdir/harris/harris.bsa6`
It would have to be reordered before attempting to try it out.  Do you know how to use the reorder tool?

**Comment by dillonhuff** [comment]
I dont. Is there just a script somewhere? I think we mentioned it in another github issue.

**Comment by dillonhuff** [comment]
Great news about the bitstream getting generated though!

**Comment by dillonhuff** [comment]
I just used the ```./verilator/generator_z_tb/bin/reorder.csh``` script to create a reordered version of harris. The code seems to run! No idea if the results are plausible. I assume Jeff has halide code that we could check against?

**Comment by steveri** [comment]
@dillonhuff @jeffsetter  Whoa!  That's crazy that it runs (crazy in a good way).  Yes, check with Jeff to see if results look plausible.  Have you looked at the output pixels, i.e. are they all zero or is there variation?  I expect there would be some large number of garbage pixels (like at least a line or two worth) before real results come out...ask Jeff what input image size is assumed, length of each linebuffer line etc.

Correct results are not strictly required for your purposes however, yes?  I.e. you just want to compare verilator runtime to that of your simulator?

**Comment by dillonhuff** [comment]
I was surprised too.

The data I put in was just a sequence 0, 1, 2, 3, ... for 100,000 cycles. Using VCS the results vary from cycle to cycle, either ```0000000011111111``` or ```0000000000000000```.

This seems plausible but it would be good if we could get a real image and compare to see if the app is running correctly. To benchmark everything does not have to be correct, but the workload needs to be the same as the correct app. If a tile is configured to be a passthrough when it should be an op, or if the app is not correctly connected that is a problem.

**Comment by dillonhuff** [comment]
@steveri do you know what LUT values are needed to make the app run? Will harris work if the LUT output is hardcoded to 1 or are other values used?

**Comment by steveri** [comment]
> Using VCS the results vary from cycle to cycle, either 0000000011111111 or 0000000000000000.

Whoa.  This is great!  It looks like it is actually finding corners!!!

@jeffsetter what workload (input image) do you use when you run harris?

**Comment by dillonhuff** [comment]
@steveri that does answer my question. Thanks!

**Comment by steveri** [comment]
Harris is working now, I am going to go ahead and close this very old issue...
